# Generated by Django 5.2 on 2025-11-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
